### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by fefelovdenis** [astrosander/LEDeffects#1]
hi! 
MAIN:19:1: error: 'EncButton' is not a template
MAIN:19:11: error: 'EB_TICK' was not declared in this scope
C:\Users\denis\OneDrive\Документы\Arduino\tgled\MAIN\MAIN.ino:19:11: note: suggested alternative: 'EB_CLICK'
C:\Users\denis\OneDrive\Документы\Arduino\tgled\MAIN\MAIN.ino: In function 'void blink(int)':
MAIN:72:18: error: 'LED_BUILTIN' was not declared in this scope
C:\Users\denis\OneDrive\Документы\Arduino\tgled\MAIN\MAIN.ino: In function 'void setup()':
MAIN:172:11: error: 'LED_BUILTIN' was not declared in this scope
C:\Users\denis\OneDrive\Документы\Arduino\tgled\MAIN\Button.ino: In function 'void ButtonTick()':
Button:4:10: error: 'class EncButton' has no member named 'held'; did you mean 'hold'?
C:\Users\denis\OneDrive\Документы\Arduino\tgled\MAIN\TBot.ino: In function 'Color Saturation(Color, int)':
TBot:80:25: error: no matching function for call to 'HardwareSerial::println(CRGB&)'
In file included from C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Stream.h:26,
                 from C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Arduino.h:177,
                 from sketch\MAIN.ino.cpp:1:
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:96:12: note: candidate: 'size_t Print::println(const __FlashStringHelper*)'
     size_t println(const __FlashStringHelper *ifsh) { return println(reinterpret_cast<const char *>(ifsh)); }
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:96:12: note:   no known conversion for argument 1 from 'CRGB' to 'const __FlashStringHelper*'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:97:12: note: candidate: 'size_t Print::println(const String&)'
     size_t println(const String &s);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:97:12: note:   no known conversion for argument 1 from 'CRGB' to 'const String&'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:98:12: note: candidate: 'size_t Print::println(const char*)'
     size_t println(const char[]);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:98:12: note:   no known conversion for argument 1 from 'CRGB' to 'const char*'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:99:12: note: candidate: 'size_t Print::println(char)'
     size_t println(char);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:99:12: note:   no known conversion for argument 1 from 'CRGB' to 'char'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:100:12: note: candidate: 'size_t Print::println(unsigned char, int)'
     size_t println(unsigned char, int = DEC);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:100:12: note:   no known conversion for argument 1 from 'CRGB' to 'unsigned char'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:101:12: note: candidate: 'size_t Print::println(int, int)'
     size_t println(int, int = DEC);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:101:12: note:   no known conversion for argument 1 from 'CRGB' to 'int'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:102:12: note: candidate: 'size_t Print::println(unsigned int, int)'
     size_t println(unsigned int, int = DEC);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:102:12: note:   no known conversion for argument 1 from 'CRGB' to 'unsigned int'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:103:12: note: candidate: 'size_t Print::println(long int, int)'
     size_t println(long, int = DEC);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:103:12: note:   no known conversion for argument 1 from 'CRGB' to 'long int'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:104:12: note: candidate: 'size_t Print::println(long unsigned int, int)'
     size_t println(unsigned long, int = DEC);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:104:12: note:   no known conversion for argument 1 from 'CRGB' to 'long unsigned int'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:105:12: note: candidate: 'size_t Print::println(long long int, int)'
     size_t println(long long, int = DEC);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:105:12: note:   no known conversion for argument 1 from 'CRGB' to 'long long int'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:106:12: note: candidate: 'size_t Print::println(long long unsigned int, int)'
     size_t println(unsigned long long, int = DEC);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:106:12: note:   no known conversion for argument 1 from 'CRGB' to 'long long unsigned int'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:107:12: note: candidate: 'size_t Print::println(double, int)'
     size_t println(double, int = 2);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:107:12: note:   no known conversion for argument 1 from 'CRGB' to 'double'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:108:12: note: candidate: 'size_t Print::println(const Printable&)'
     size_t println(const Printable&);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:108:12: note:   no known conversion for argument 1 from 'CRGB' to 'const Printable&'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:109:12: note: candidate: 'size_t Print::println(tm*, const char*)'
     size_t println(struct tm * timeinfo, const char * format = NULL);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:109:12: note:   no known conversion for argument 1 from 'CRGB' to 'tm*'
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:110:12: note: candidate: 'size_t Print::println()'
     size_t println(void);
            ^~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Print.h:110:12: note:   candidate expects 0 arguments, 1 provided
C:\Users\denis\OneDrive\Документы\Arduino\tgled\MAIN\TBot.ino: In function 'void connectWiFi()':
TBot:137:49: error: no matching function for call to 'WiFiClass::hostname()'
In file included from C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\WiFi\src/WiFiSTA.h:28,
                 from C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\WiFi\src/WiFi.h:32,
                 from C:\Users\denis\Documents\libraries\FastBot\src/FastBot.h:146,
                 from C:\Users\denis\OneDrive\Документы\Arduino\tgled\MAIN\MAIN.ino:13:
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\WiFi\src/WiFiGeneric.h:195:17: note: candidate: 'static bool WiFiGenericClass::hostname(const String&)'
     static bool hostname(const String& aHostname) { return setHostname(aHostname.c_str()); }
                 ^~~~~~~~
C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\WiFi\src/WiFiGeneric.h:195:17: note:   candidate expects 1 argument, 0 provided
C:\Users\denis\OneDrive\Документы\Arduino\tgled\MAIN\TBot.ino: In function 'void newMsg(FB_msg&)':
TBot:264:16: error: 'LED_BUILTIN' was not declared in this scope
Несколько библиотек найдено для "WiFi.h"
 Используется: C:\Users\denis\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\WiFi
Не используется: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
'EncButton' is not a template

**Comment by astrosander** [comment]
Good afternoon,
1. Be sure you selected ESP-8266 Nodemcu in the Board Manager
2. Reinstall libraries:
  Open <a href="https://github.com/astrosander/LEDeffects/blob/main/libraries">./libraries</a> and copy all of them to ```%ArduinoFolder%/libraries```
3. Then, reopen and try again

Sincerely, Aliaksandr Melnichenka

**Comment by fefelovdenis** [comment]
добрый день!
 error: 'class ESP8266HTTPUpdate' has no member named 'updateFS'
         else if (OTAflag == FB_SPIFFS) OTAstate = ESPhttpUpdate.updateFS(client, *_file_ptr);
теперь вот такая ошибка... 
может версия ide не такая? или ядро платы? ide 1.8.19 esp 2.5.2

**Comment by astrosander** [comment]
I use `Arduino IDE 1.8.19` and `ESP-8266 3.1.2`

Please, try to change ESP's version to `3.1.2`

**Comment by astrosander** [comment]
For correct work you needed to select a correct compiling parameters. Here is something about my IDE:
`Arduino IDE 1.8.19` 
`ESP-8266 3.1.2`
